version: '3'
services:
  employees-mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees
      MYSQL_ALLOW_EMPTY_PASSWORD: yes