version: '3'
services:
  vaccination-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vaccination
      MYSQL_USER: vaccination
      MYSQL_PASSWORD: vaccination
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  vaccination-test-mysql:
        image: mysql:latest
        ports:
          - "3308:3306"
        environment:
          MYSQL_DATABASE: vaccination_test
          MYSQL_USER: vaccination_test
          MYSQL_PASSWORD: vaccination_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes