version: '3'
services:
  employees-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command:
      --init-file /data/application/initdb.sql
    volumes:
      - ./db/initdb.sql:/data/application/initdb.sql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: yes